version: "3.9"

services:
  telegram_bot:
    # Собирать образ из Dockerfile текущей директории
    build: .
    
    # Название контейнера (необязательно, но удобно для чтения)
    container_name: telegram_bot

    # Файл с переменными окружения
    env_file:
      - stack.env

    # Если хотите пробрасывать исходники с хост-машины (чтобы изменять код без пересборки):
    volumes:
      - ./app:/app
      
    working_dir: /app

    # Запускаем main.py внутри контейнера (можно пропустить, если CMD в Dockerfile уже указан)
    command: python main.py
